name = "x-gx-h-gallery-api"
main = "src/index.js"
compatibility_date = "2026-09-18"

[vars]
ALLOWED_ORIGINS = "https://guoxuan-li.github.io"

[[kv_namespaces]]
binding = "GALLERY_IMAGES"
id = "7644d36c0bfc4373b651afefa85e249e"

[[d1_databases]]
binding = "GALLERY_DB"
database_name = "x-gx-h-gallery"
database_id = "1d04bf5b-c7d3-4ef8-b33a-7773086e0da9"
